(ns et.pe.ds
  (:require [et.pe.ds.sqlite :as sqlite]))

(defn init-conn [type opts] (sqlite/init-conn type opts))
(defn close-conn [conn] (sqlite/close-conn conn))
(defn get-persona-by-id [conn id] (sqlite/get-persona-by-id conn id))
(defn get-persona-by-email [conn email] (sqlite/get-persona-by-email conn email))
(defn get-persona-by-id-or-email [conn id email] (sqlite/get-persona-by-id-or-email conn id email))
(defn add-persona [conn id email password-hash persona-name] (sqlite/add-persona conn id email password-hash persona-name))
(defn update-persona [conn id updates] (sqlite/update-persona conn id updates))
(defn get-persona-password-hash [conn id] (sqlite/get-persona-password-hash conn id))
(defn list-personas [conn] (sqlite/list-personas conn))
(defn list-identities [conn persona] (sqlite/list-identities conn persona))
(defn get-identity [conn persona identity-id] (sqlite/get-identity conn persona identity-id))
(defn list-recent-identities [conn persona limit offset] (sqlite/list-recent-identities conn persona limit offset))
(defn add-identity [conn persona nm text & [opts]] (sqlite/add-identity conn persona nm text opts))
(defn update-identity [conn persona id nm text & [opts]] (sqlite/update-identity conn persona id nm text opts))
(defn get-identity-at [conn persona id time-point] (sqlite/get-identity-at conn persona id time-point))
(defn get-identity-history [conn persona id] (sqlite/get-identity-history conn persona id))
(defn add-relation [conn persona source-id target-id & [opts]] (sqlite/add-relation conn persona source-id target-id opts))
(defn list-relations [conn persona source-id & [opts]] (sqlite/list-relations conn persona source-id opts))
(defn delete-relation [conn persona relation-id & [opts]] (sqlite/delete-relation conn persona relation-id opts))
(defn search-identities [conn persona query & [opts]] (sqlite/search-identities conn persona query opts))
