(ns et.pe.ds
  (:require [et.pe.ds.sqlite :as sqlite]))

(defn init-conn [type opts] (sqlite/init-conn type opts))
(defn close-conn [conn] (sqlite/close-conn conn))
(defn get-account [conn account-id] (sqlite/get-account conn account-id))
(defn get-account-by-email [conn email] (sqlite/get-account-by-email conn email))
(defn add-account [conn email password-hash] (sqlite/add-account conn email password-hash))
(defn get-account-password-hash [conn account-id] (sqlite/get-account-password-hash conn account-id))
(defn list-accounts [conn] (sqlite/list-accounts conn))
(defn get-persona-by-id [conn id] (sqlite/get-persona-by-id conn id))
(defn add-persona [conn account-id id persona-name] (sqlite/add-persona conn account-id id persona-name))
(defn update-persona [conn id updates] (sqlite/update-persona conn id updates))
(defn delete-persona [conn id] (sqlite/delete-persona conn id))
(defn list-personas [conn] (sqlite/list-personas conn))
(defn list-personas-for-account [conn account-id] (sqlite/list-personas-for-account conn account-id))
(defn list-identities [conn persona] (sqlite/list-identities conn persona))
(defn get-identity [conn persona identity-id] (sqlite/get-identity conn persona identity-id))
(defn list-recent-identities [conn persona limit offset] (sqlite/list-recent-identities conn persona limit offset))
(defn add-identity [conn persona nm text & [opts]] (sqlite/add-identity conn persona nm text opts))
(defn update-identity [conn persona id nm text & [opts]] (sqlite/update-identity conn persona id nm text opts))
(defn save-identity-version [conn persona id nm text & [opts]] (sqlite/save-identity-version conn persona id nm text opts))
(defn get-identity-at [conn persona id time-point] (sqlite/get-identity-at conn persona id time-point))
(defn get-identity-history [conn persona id] (sqlite/get-identity-history conn persona id))
(defn list-relations [conn persona source-id & [opts]] (sqlite/list-relations conn persona source-id opts))
(defn search-identities [conn persona query & [opts]] (sqlite/search-identities conn persona query opts))
