(ns et.pe.ds
  (:require [et.pe.ds.sqlite :as sqlite]))

(defn init-conn [type opts] (sqlite/init-conn type opts))
(defn close-conn [conn] (sqlite/close-conn conn))
(defn get-account [conn account-id] (sqlite/get-account conn account-id))
(defn get-account-by-email [conn email] (sqlite/get-account-by-email conn email))
(defn add-account [conn email password-hash] (sqlite/add-account conn email password-hash))
(defn get-account-password-hash [conn account-id] (sqlite/get-account-password-hash conn account-id))
(defn list-accounts [conn] (sqlite/list-accounts conn))
(defn get-persona-by-id [conn id] (sqlite/get-persona-by-id conn id))
(defn add-persona [conn account-id id persona-name] (sqlite/add-persona conn account-id id persona-name))
(defn update-persona [conn id updates] (sqlite/update-persona conn id updates))
(defn delete-persona [conn id] (sqlite/delete-persona conn id))
(defn list-personas [conn] (sqlite/list-personas conn))
(defn list-personas-for-account [conn account-id] (sqlite/list-personas-for-account conn account-id))
(defn add-machine-user [conn account-id nm opts] (sqlite/add-machine-user conn account-id nm opts))
(defn get-machine-user [conn nm] (sqlite/get-machine-user conn nm))
(defn get-machine-user-by-id [conn account-id] (sqlite/get-machine-user-by-id conn account-id))
(defn get-machine-user-by-token-hash [conn token-hash] (sqlite/get-machine-user-by-token-hash conn token-hash))
(defn set-machine-token-hash! [conn account-id token-hash] (sqlite/set-machine-token-hash! conn account-id token-hash))
(defn update-machine-user [conn account-id updates] (sqlite/update-machine-user conn account-id updates))
(defn delete-machine-user [conn account-id] (sqlite/delete-machine-user conn account-id))
(defn list-machine-users [conn account-id] (sqlite/list-machine-users conn account-id))
(defn grant-persona [conn account-id persona-id] (sqlite/grant-persona conn account-id persona-id))
(defn revoke-persona [conn account-id persona-id] (sqlite/revoke-persona conn account-id persona-id))
(defn granted-personas [conn account-id] (sqlite/granted-personas conn account-id))
(defn machine-may-write? [conn account-id persona-id] (sqlite/machine-may-write? conn account-id persona-id))
(defn list-identities [conn persona] (sqlite/list-identities conn persona))
(defn get-identity [conn persona identity-id] (sqlite/get-identity conn persona identity-id))
(defn list-recent-identities [conn persona limit offset] (sqlite/list-recent-identities conn persona limit offset))
;; `author` is positional on the three writes below, and stays positional as it
;; is passed on: see the write section of ds.sqlite for why the loud failure
;; belongs in the signature rather than in a default nobody sees.
(defn add-identity [conn persona nm text author & [opts]] (sqlite/add-identity conn persona nm text author opts))
(defn update-identity [conn persona id nm text author & [opts]] (sqlite/update-identity conn persona id nm text author opts))
(defn save-identity-version [conn persona id nm text author & [opts]] (sqlite/save-identity-version conn persona id nm text author opts))
(defn get-identity-at [conn persona id time-point] (sqlite/get-identity-at conn persona id time-point))
(defn get-identity-history [conn persona id] (sqlite/get-identity-history conn persona id))
(defn list-relations [conn persona source-id & [opts]] (sqlite/list-relations conn persona source-id opts))
(defn search-identities [conn persona query & [opts]] (sqlite/search-identities conn persona query opts))
